steps:
- name: Build & publish (amd64)
  privileged: true
  image: woodpeckerci/plugin-docker-buildx
  settings:
    auto_labels: false
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    build_args: "GIT_COMMIT=${CI_COMMIT_SHA}"
    repo: handspiker2/sonarr-connector
    tags: latest
    dry_run: false
    platforms: [linux/amd64]
  when:
    branch:
    - master

# Just test build branches
- name: Build (x86_64)
  privileged: true
  image: woodpeckerci/plugin-docker-buildx
  settings:
    auto_labels: false
    build_args: "GIT_COMMIT=${CI_COMMIT_SHA}"
    repo: handspiker2/sonarr-connector
    tags: latest
    dry_run: true
    platforms: [linux/amd64]
  when:
    branch:
      exclude:
      - master
